/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import static Views.DashboardProducts.cardLayout;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.util.StringUtils;
import com.google.protobuf.Message;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.print.attribute.standard.PresentationDirection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.UserSession;

/**
 *
 * @author Carlos Fabricio
 */
public class Dashboard extends javax.swing.JFrame implements DashboardInterface{

    private CardLayout cardLayout;
    private boolean isAdmin;
    
    /**
     * Creates new form DashboardProductos
     */
    public Dashboard() {
        
        cardLayout = new CardLayout();
        initComponents();
        
        /* Get fate information */
        LocalDate now = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE d 'de' MMMM 'del año' yyyy", new Locale("es", "ES"));
        String formattedDate = "Hoy es " + now.format(formatter);
        lblDateInformation.setText(formattedDate);
        
        /* get user information */
        String username = UserSession.getUsername();
        lblWelcome.setText("Bienvenido "+ username);
        loadInformation();
        
        cardLayout = (CardLayout)panContent.getLayout();
        
        JPanel cataloguePanel = new Products();
        JPanel inicioPanel = new Principal();
        JPanel reportsPanel = new Reports();
        
        JPanel mantenimientosPanel = new MantenimientosPreview(this);
        JPanel productPanel = new ProductPanel(this);
        JPanel categoriesPanel = new CategoriesPanel(this);
        JPanel Usuarios = new Views.Usuarios();
        JPanel orderPanel = new OrderPanel();

        /* Vista de clientes*/
        panContent.add(inicioPanel, "Inicio");
        panContent.add(cataloguePanel, "Catalogue");
        
        /* Vista de administradors */
        panContent.add(mantenimientosPanel, "Mantenimientos");
        panContent.add(productPanel, "Productos");
        panContent.add(Usuarios, "Usuarios");
        panContent.add(categoriesPanel, "Categorias");
        panContent.add(orderPanel, "Ordenes");
        panContent.add(reportsPanel, "Reportes");
        
        initContet();
    }
    
    /* Load information */
    private void loadInformation(){
        if (UserSession.getRole() == 2) isAdmin = true;
        else{   
            isAdmin = false;   
            btnMantenimientos.setEnabled(false);
            btnUsuarios.setEnabled(false);
            btnOrdersPan.setEnabled(false);
            btnReports.setEnabled(false);
            lblWelcome.setVisible(false);
        }
        
        if(StringUtils.isEmpty(UserSession.getUsername()))  btnSession.setText("Iniciar sesión");
        else btnSession.setText("Cerrar sesión");
        
    }
    
    private void initContet() {
        switchPanel("Inicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBackground = new javax.swing.JPanel();
        panMenu = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnMantenimientos = new javax.swing.JButton();
        btnOrdersPan = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPrincipalPan = new javax.swing.JButton();
        btnCatalogue = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDateInformation = new javax.swing.JLabel();
        panContent = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnSession = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 400));

        panBackground.setBackground(new java.awt.Color(255, 255, 255));

        panMenu.setBackground(new java.awt.Color(255, 0, 0));
        panMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuarios.setBackground(new java.awt.Color(255, 0, 0));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-ico.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setIconTextGap(10);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        panMenu.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 51));
        panMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 106, 237, -1));

        btnMantenimientos.setBackground(new java.awt.Color(255, 0, 0));
        btnMantenimientos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMantenimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnMantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-product-30.png"))); // NOI18N
        btnMantenimientos.setText("Mantenimientos");
        btnMantenimientos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnMantenimientos.setBorderPainted(false);
        btnMantenimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMantenimientos.setIconTextGap(10);
        btnMantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientosActionPerformed(evt);
            }
        });
        panMenu.add(btnMantenimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 251, 280, 50));

        btnOrdersPan.setBackground(new java.awt.Color(255, 0, 0));
        btnOrdersPan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOrdersPan.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdersPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/order-ico.png"))); // NOI18N
        btnOrdersPan.setText("Ordenes");
        btnOrdersPan.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnOrdersPan.setBorderPainted(false);
        btnOrdersPan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdersPan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOrdersPan.setIconTextGap(10);
        btnOrdersPan.setMaximumSize(new java.awt.Dimension(135, 70));
        btnOrdersPan.setMinimumSize(new java.awt.Dimension(135, 70));
        btnOrdersPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersPanActionPerformed(evt);
            }
        });
        panMenu.add(btnOrdersPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 280, 50));

        btnReports.setBackground(new java.awt.Color(255, 0, 0));
        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hexagon-svgrepo-com.png"))); // NOI18N
        btnReports.setText("Reportes");
        btnReports.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnReports.setBorderPainted(false);
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReports.setIconTextGap(10);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        panMenu.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 280, 51));

        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BodeBandidos S.A.C");
        panMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 51, 214, 43));

        btnPrincipalPan.setBackground(new java.awt.Color(255, 0, 0));
        btnPrincipalPan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipalPan.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipalPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/categoryico.png"))); // NOI18N
        btnPrincipalPan.setText("Inicio");
        btnPrincipalPan.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnPrincipalPan.setBorderPainted(false);
        btnPrincipalPan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipalPan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipalPan.setIconTextGap(10);
        btnPrincipalPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalPanActionPerformed(evt);
            }
        });
        panMenu.add(btnPrincipalPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, 51));

        btnCatalogue.setBackground(new java.awt.Color(255, 0, 0));
        btnCatalogue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCatalogue.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalogue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hexagon-svgrepo-com.png"))); // NOI18N
        btnCatalogue.setText("Catalogo");
        btnCatalogue.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnCatalogue.setBorderPainted(false);
        btnCatalogue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatalogue.setIconTextGap(10);
        btnCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogueActionPerformed(evt);
            }
        });
        panMenu.add(btnCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 51));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 351));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDateInformation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDateInformation.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblDateInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 46, 648, 29));

        panContent.setBackground(new java.awt.Color(255, 255, 255));
        panContent.setRequestFocusEnabled(false);
        panContent.setLayout(new java.awt.CardLayout());

        lblWelcome.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        lblWelcome.setText("¡Bienvenido de vuelta!");

        btnSession.setBackground(new java.awt.Color(255, 0, 0));
        btnSession.setForeground(new java.awt.Color(255, 255, 255));
        btnSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBackgroundLayout = new javax.swing.GroupLayout(panBackground);
        panBackground.setLayout(panBackgroundLayout);
        panBackgroundLayout.setHorizontalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSession, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
        );
        panBackgroundLayout.setVerticalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWelcome)
                    .addComponent(btnSession, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSessionActionPerformed
        if (StringUtils.isEmpty(UserSession.getUsername())) {
            
            Login dp = new Login();
            dp.setVisible(true);
            dispose();
            
        }else{
            //Se cerrara la sesión
            UserSession.clearSession();

            Dashboard dp = new Dashboard();
            dp.setVisible(true);
            dispose();
            
        }        

    }//GEN-LAST:event_btnSessionActionPerformed

    private void btnCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogueActionPerformed
        switchPanel("Catalogue");
    }//GEN-LAST:event_btnCatalogueActionPerformed

    private void btnPrincipalPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalPanActionPerformed
        switchPanel("Inicio");
    }//GEN-LAST:event_btnPrincipalPanActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        if (isAdmin) switchPanel("Reportes");
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnOrdersPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersPanActionPerformed
        if (isAdmin) switchPanel("Ordenes");
    }//GEN-LAST:event_btnOrdersPanActionPerformed

    private void btnMantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientosActionPerformed
        if (isAdmin) switchPanel("Mantenimientos");
    }//GEN-LAST:event_btnMantenimientosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        if (isAdmin) switchPanel("Usuarios");
    }//GEN-LAST:event_btnUsuariosActionPerformed

    @Override    
    public void switchPanel(String panelName) {
        cardLayout.show(panContent, panelName);
    }

    /*    
        public void ShowJPanel(JPanel p){
            p.setSize(000, 400);
            p.setLocation(0,0);

            panContent.removeAll();
            panContent.add(p, BorderLayout.CENTER);
            panContent.revalidate();
            panContent.repaint();   
        }
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogue;
    private javax.swing.JButton btnMantenimientos;
    private javax.swing.JButton btnOrdersPan;
    private javax.swing.JButton btnPrincipalPan;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSession;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDateInformation;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panBackground;
    private javax.swing.JPanel panContent;
    private javax.swing.JPanel panMenu;
    // End of variables declaration//GEN-END:variables

}
